### ISSUE TITLE
Write the details notes on the discretization of neoclassical growth (using the established notation)

### ISSUE THREAD

**Issue by jlperla** [econtoolkit/continuous_time_methods#23]
I want to ensure that `/docs/HJBE_discretization.tex` has a complete set of algebra for the system of equations.  I would like to write things in the notation of `/docs/operator_discretization_finite_differences.tex`  For example, using $\mu^+$ and the $X,Y,Z$ matrices for the upwind procedure - though that will simplify due to the lack of diffusion.

After this, #2 becomes possible as the next step.

**Comment by jlperla** [comment]
A few comments and questions:
-  I made a small change to your notation which you should check carefully: I multiplied the definition of X,Y,Z,B,A by $\Delta$.  Please check that I did not make any mistakes.
- In calculating (26), we need to have a $c^n$.  Where formula should we use exactly?  Clearly it has something to do with (4) but which version of the derivative do we use (i.e. maybe using (19)?
- I just wanted to verify that this procedure requires the calculation of the steady state , and that there is no way to get it to pop out of the solution as an outcome.  The only place I see it come in is (19), which I think is used to calculate $c^n$.  Is that correct?

**Comment by sariwxy** [comment]
Regarding previous comment: 
- Everything seems to be correct here. From checking the algebra, the deltas should all cancel out to give the same results as before the multiplication. 
- Equation (19)  is the version of the derivative used (corresponding to dV_Upwind in the matlab code). This derivative is then plugged into (4) to acquire (26). I've updated the notes to clarify this point. 
-  Yes, (19) is the only place the steady state comes in. Since it is used in (19) to generate the approximation upon which the rest of the procedure is based, I don't think it's possible for it to occur as a natural result without changing the method. 
The only other time it's mentioned is early on when defining the grid ($k_1$ should be less than the steady state capital, and $k_I$ greater) but it isn't really necessary there.
