### ISSUE TITLE
Get the `DiffEqOperators.jl` environment setup

### ISSUE THREAD

**Issue by jlperla** [econtoolkit/continuous_time_methods#42]
Talk to Chris R about this as required to get the full DiffEqOperators setup.  In the background, worth watching his tutorial to get a sense of how this stuff works: https://www.youtube.com/watch?v=tx8DRc7_c9I&amp=&t=2s

For our own simple testing setup, I will leave things much more open.

**Comment by FernandoKuwer** [comment]
Ok, I will watch the video later today (I have a meeting up to 3:00) and then I'll contact Chris about the full setup.

**Comment by jlperla** [comment]
Sounds good.  No need to watch the parts about creating a new package, as yours would already be setup, but good to get a sense of how pull requests, etc. work.

**Comment by FernandoKuwer** [comment]
Hi Jesse, I finished watching the video and I have a few questions: 
1) Are we forking Chris's package to work on it? 
2) When I'm working on a task (for example, the issue #41 that I will work after Family Day), should I create a new branch and make a pull request after finishing it?
3) When you mention to "get the DiffEqOperators.jl environment setup", what exactly do you mean: just installing GitKraken and cloning the package? If so, why is it required to talk with Chris - nothing against talking with him (on the contrary!). I'm not sure if I understood the task correctly

**Comment by jlperla** [comment]
1. Not forking, adding the functionality to the package (though I think you
need to fork it to do pull requests, etc). Chris is going to help out on
the interface design, etc.

I don't know the git or Julia package workflow, so wanted you to see how it
would work for testing, etc. Once you figure out the workflow for editing
the code and tests, I would love to see it! I think there is a package
called Revise.jl which helps

2. Sorry, I meant to do a simple test package for us to mess around with
(so we aren't putting everything into the package itself). But that isn't
strictly necessary. You may just feel more comfortable working out of pull
requests on the main repo

3. As the manager of the repo with commit access, Chris can help you with
the structure etc of adding in the functionality. I discussed some of this
with him today on what we would try to accomplish as first steps (which we
can discuss after family day)

He is "the boss" as far as I am concerned on the code itself, merging pull
requests, etc. I will be much more useful for thinking about how economists
would use it

I may bring other people into the mix as well, since there is a lot of
demand for this functionality.

**Comment by FernandoKuwer** [comment]
Hi Jesse! 
1) Just talked with Chris: now I think I understood how he plans to work in the DiffEqOpperator library. Also, he told me he is preparing a video tutorial on it. If you want, we could meet so I could explain his preferred workflow (it's just like the one in the video, based on creating branches on GitKraken).
2) Today I spend the morning reading more about code testing (this was a somewhat foreign concept to me - now I think that I'm understanding it better). Nonetheless, I have a question: what kind of tests are you planning to include in the #40 ? I ask that because this would likely impact how should I write #41. 
3) About issue #41 : do you want me to wait for #40 or should I start working on it? (I could start today after class).

Also, since I already talked with Chris, should I close this issue?
Cheers

**Comment by jlperla** [comment]
Perfect, I will close it.  For #40 I think I will close it.  Instead of setting up a test environment, why don't we work directly with Chris's planned workflow for now.  We can open one up later if need-be.
